# **Ejercicios**

Hecho por: Santiago Tinoco Román y Alejandra Fuentes

Geología VIII semestre

## Ejercicio 1

1. **Calcular el factorial**: Obtenga el resultado de multiplicar los números del 1 al $n$ (factorial de $n$). Implemente una función que realice este cálculo.

2. **Matriz comparativa de vectores aleatorios**: 
   - Cree dos vectores $V_1$ y $V_2$ de tamaño $n$ con números aleatorios entre 1 y 10
   - Genere un vector $V_3$ donde:
     - $V_3[i] = 0$ si $V_1[i] < V_2[i]$
     - $V_3[i] = 1$ en caso contrario
   - Concatene los tres vectores ($V_1$, $V_2$, $V_3$) como columnas para obtener una matriz de dimensiones $(n \times 3)$

In [1]:
#Ejercicio 1.1

def factorial(n: int) -> int:
    """Calcula el factorial del número dado"""
    if n == 0:
            return 1
    else:
        return n * factorial(n - 1)

num = int(input("Ingrese un número entero: "))

print(f"El factorial de {num} es: {factorial(num)}")

El factorial de 5 es: 120


In [2]:
#Ejercicio 1.2

import numpy as np

n = int(input("Ingrese un número entero positivo: "))

v1 = np.array([np.random.randint(1, 10) for i in range(n)], dtype=int)
v2 = np.array([np.random.randint(1, 10) for i in range(n)], dtype=int)

v3 = np.array([], dtype=int)
for i in range(len(v1)):
    if v1[i] < v2[i]:
        v3 = np.append(v3, 0)
    else:
        v3 = np.append(v3, 1)

print(f"Vector 1: {v1}")
print(f"Vector 2: {v2}")
print(f"Vector 3: {v3}")


matriz = np.concatenate([v1[:, None], v2[:, None], v3[:, None]], axis=1)
print(f"La matriz resultante, siendo cada vector una columna es:\n{matriz}")

Vector 1: [2 2 3 2 1]
Vector 2: [3 3 6 3 5]
Vector 3: [0 0 0 0 0]
La matriz resultante, siendo cada vector una columna es:
[[2 3 0]
 [2 3 0]
 [3 6 0]
 [2 3 0]
 [1 5 0]]


## Ejercicio 2

Dado valores $m$ (número de filas) y $n$ (número de columnas), realice las siguientes tareas:

1. **Crear matriz de ceros**: Genere una matriz $A$ de dimensiones $(m \times n)$ inicializada con ceros.

2. **Llenar matriz con números aleatorios (usando `while`)**: 
   - Utilizando un bucle `while`, reemplace cada columna de la matriz $A$ por vectores de números aleatorios enteros en el rango $[-1, 3]$
   - Recorra columna por columna

3. **Transformar elementos (usando `while`)**: 
   - Utilizando dos bucles `while` anidados, recorra todos los elementos de la matriz
   - Reemplace los elementos **negativos** por $-1$
   - Reemplace los elementos **no negativos** (cero o positivos) por $5$

4. **Repetir transformación (usando `for`)**: 
   - Realice el mismo ejercicio del paso 3, pero esta vez utilizando dos bucles `for` anidados
   - Compare los resultados para verificar que ambos métodos producen la misma matriz


In [3]:
import numpy as np

m = int(input("Ingrese el número de filas de la matriz: "))
n = int(input("Ingrese el número de columnas de la matriz: "))

#1
A = np.zeros((m, n), dtype=int)

#2
col = 0
while col < A.shape[1]:
    A[:, col] = np.random.randint(-1, 4, size=A.shape[0])
    col += 1
print(f"La matriz generada de ceros es:\n{A}", end="\n\n")

#3
matriz_1 = A.copy()
col = 0
fil = 0
while col < matriz_1.shape[1]:
    while fil < matriz_1.shape[0]:
        if matriz_1[fil, col] < 0:
            matriz_1[fil, col] = -1
        else:
            matriz_1[fil, col] = 5
        fil += 1
    fil = 0
    col += 1

print(f"La matriz usando el ciclo while es:\n{matriz_1}", end="\n\n")

#4
matriz_2 = A.copy()
for i in range(matriz_2.shape[0]):
    for j in range(matriz_2.shape[1]):
        if matriz_2[i, j] == -1:
            matriz_2[i, j] = -1
        else:
            matriz_2[i, j] = 5

print(f"La matriz usando el ciclo for es:\n{matriz_2}", end="\n\n")
print(f"Comparando las matrices resultantes de los métodos 3 y 4, son iguales?: {np.array_equal(matriz_1, matriz_2)}")

La matriz generada de ceros es:
[[ 3  0  1]
 [-1  2  1]
 [ 2  3  0]
 [ 3  3  1]]

La matriz usando el ciclo while es:
[[ 5  5  5]
 [-1  5  5]
 [ 5  5  5]
 [ 5  5  5]]

La matriz usando el ciclo for es:
[[ 5  5  5]
 [-1  5  5]
 [ 5  5  5]
 [ 5  5  5]]

Comparando las matrices resultantes de los métodos 3 y 4, son iguales?: True


## Ejercicio 3
Se recolectaron datos de 8 estudiantes universitarios y se resumieron en la siguiente tabla:

<div align="center">

|MASA| ESTATURA| GENERO| ESTRATO |FUMA|
|----|---------|--------|--------|----|
|71 |183| HOMBRE |2| NO|
|45| 168 |HOMBRE| 1 |NO|
|50| 164 |HOMBRE| 1 |NO|
|60| 164 |MUJER |3 |SI|
|61| 167 |HOMBRE| 3| SI|
|84| 182 |HOMBRE| 3| NO|
|55| 168 |MUJER |3 |NO|
|60| 170 |HOMBRE| 3 |SI|

</div>

1. Crear un data frame y llamarlo __df__.
2. Realizar un análisis descriptivo básico de todas las variables.
3. Extraer un subconjunto de datos con los primeros 4 estudiantes y llamarlo __subc1__.
4. Extraer las variables categóricas y guardarlas en un subconjunto llamado __subc2__
5. Extraer las variables numéricas y guardarlas en un subconjunto llamado __subc3__

In [4]:
import pandas as pd
import numpy as np

df = pd.DataFrame({
    "Masa": [71, 45, 50, 60, 61, 84, 55, 60],
    "Estatura": [183, 168, 164, 164, 167, 182, 168, 170],
    "Genero": ["Hombre", "Hombre", "Hombre", "Mujer", "Hombre", "Hombre", "Mujer", "Hombre"],
    "Estrato": [2, 1, 1, 3, 3, 3, 3, 3],
    "Fuma": ["No", "No", "No", "Si", "Si", "No", "No", "Si"]
})

print(df)

print("\n")

print(f"El promedio de las masas de los 8 estudiantes es: {np.mean(df['Masa'])}\n")
print(f"El promedio de las estaturas de los 8 estudiantes es: {np.mean(df['Estatura'])}\n")
print(f"Conteo de géneros:\n{df['Genero'].value_counts()}\n Siendo el genero más frecuente: {df['Genero'].mode()[0]}\n")
print(f"Conteo de estratos:\n{df['Estrato'].value_counts()}\n Siendo el estrato más frecuente: {df['Estrato'].mode()[0]}\n")
print(f"Conteo de fumadores:\n{df['Fuma'].value_counts()}\n Siendo la respuesta más frecuente: {df['Fuma'].mode()[0]}\n")

subc1 = df[0:4]
print(f"Subconjunto 1:\n{subc1}\n")

subc2 = df.select_dtypes(include=["object"])
print(f"Subconjunto 2:\n{subc2}\n")

subc3 = df.select_dtypes(include=["int64"])
print(f"Subconjunto 3:\n{subc3}\n")

   Masa  Estatura  Genero  Estrato Fuma
0    71       183  Hombre        2   No
1    45       168  Hombre        1   No
2    50       164  Hombre        1   No
3    60       164   Mujer        3   Si
4    61       167  Hombre        3   Si
5    84       182  Hombre        3   No
6    55       168   Mujer        3   No
7    60       170  Hombre        3   Si


El promedio de las masas de los 8 estudiantes es: 60.75

El promedio de las estaturas de los 8 estudiantes es: 170.75

Conteo de géneros:
Genero
Hombre    6
Mujer     2
Name: count, dtype: int64
 Siendo el genero más frecuente: Hombre

Conteo de estratos:
Estrato
3    5
1    2
2    1
Name: count, dtype: int64
 Siendo el estrato más frecuente: 3

Conteo de fumadores:
Fuma
No    5
Si    3
Name: count, dtype: int64
 Siendo la respuesta más frecuente: No

Subconjunto 1:
   Masa  Estatura  Genero  Estrato Fuma
0    71       183  Hombre        2   No
1    45       168  Hombre        1   No
2    50       164  Hombre        1   No
3    60